"""AI Unit 1: Rational-Agent Decision Rules & Architecture.

Implements:
1. Formal PEAS Specification:
   - Performance Measure: Utility function balancing fraud loss prevention,
     false-positive customer friction, and manual review investigation costs.
   - Environment: Partially observable, sequential, dynamic, multi-agent adversarial.
   - Actuators: APPROVE, FLAG_MANUAL_REVIEW, FREEZE_ACCOUNT.
   - Sensors: Transaction payload, account baselines, propositional logic results,
     network graph topology, equivalence relations.
2. Expected Utility Decision Policy (Rational Agent: argmax_a EU(a | Percept)).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Set
from adsa.cycle_detector import CycleDetector
from adsa.flow_analyzer import GraphFlowAnalyzer
from adsa.graph import TransactionGraph
from dmgt.propositional_engine import PropositionalLogicEngine
from dmgt.relations import AccountIdentityRelationManager
from models.account import Account
from models.transaction import Transaction
from models.types import ActionType, RiskTier, TransactionStatus


@dataclass
class Percept:
    """Sensor readings received by the agent for an incoming transaction (Sensors)."""
    transaction: Transaction
    sender_account: Account
    receiver_account: Optional[Account]
    timestamp: datetime
    # Sensor data extracted from DMGT & ADSA subsystems
    proposition_truth_values: Dict[str, bool] = field(default_factory=dict)
    linked_accounts: Set[str] = field(default_factory=set)
    involves_cycle: bool = False
    cycle_nodes: List[str] = field(default_factory=list)
    fan_in_anomaly: bool = False
    mule_pass_through: bool = False
    hops_to_blacklist: Optional[int] = None


@dataclass
class DecisionOutcome:
    """Action and rationale generated by the Rational Agent (Actuators)."""
    action: ActionType
    risk_tier: RiskTier
    posterior_fraud_probability: float
    expected_utilities: Dict[ActionType, float]
    fired_rules: List[str]
    audit_trail: List[str]


class RationalFraudScreeningAgent:
    """Utility-Based Rational Agent for First-Pass Fraud Screening (AI U1).

    Rationality Criterion: Selects action a* that maximizes Expected Utility EU(a).
    """

    def __init__(
        self,
        logic_engine: PropositionalLogicEngine,
        graph: TransactionGraph,
        relation_manager: AccountIdentityRelationManager,
        review_cost: float = 25.0,
        false_positive_penalty_multiplier: float = 0.05,
    ) -> None:
        self.logic_engine = logic_engine
        self.graph = graph
        self.relation_manager = relation_manager
        self.cycle_detector = CycleDetector(graph)
        self.flow_analyzer = GraphFlowAnalyzer(graph)

        # Economic parameters for utility evaluation
        self.review_cost = review_cost
        self.false_positive_penalty_multiplier = false_positive_penalty_multiplier

        # Internal Knowledge Base
        self.blacklisted_accounts: Set[str] = set()

    def add_to_blacklist(self, account_id: str) -> None:
        self.blacklisted_accounts.add(account_id)

    def perceive(self, txn: Transaction, sender: Account, receiver: Optional[Account]) -> Percept:
        """Sensors: Gathers observations from environment, graph, relations, and baselines."""
        # 1. Feature extractions for Propositional Logic (DMGT U1)
        # P_HIGH_AMOUNT: amount > 3x historical average
        p_high_amount = txn.amount > (3.0 * sender.historical_avg_amount)
        # P_NEW_DEVICE: device fingerprint differs from registered baseline
        p_new_device = bool(sender.device_fingerprint and txn.device_id != sender.device_fingerprint)
        # P_NEW_ACCOUNT: account age < 14 days
        p_new_account = sender.account_age_days(txn.timestamp) < 14.0
        # P_FOREIGN_LOCATION: transaction location differs from sender's standard
        p_foreign_loc = txn.location not in ("US", "DOMESTIC")
        # P_OFF_HOURS: transaction between 01:00 AM and 05:00 AM
        p_off_hours = 1 <= txn.timestamp.hour <= 5
        # P_UNVERIFIED_KYC: unverified account
        p_unverified_kyc = sender.kyc_status.value == "TIER_1_UNVERIFIED"

        assignment = {
            "P_HIGH_AMOUNT": p_high_amount,
            "P_NEW_DEVICE": p_new_device,
            "P_NEW_ACCOUNT": p_new_account,
            "P_FOREIGN_LOCATION": p_foreign_loc,
            "P_OFF_HOURS": p_off_hours,
            "P_UNVERIFIED_KYC": p_unverified_kyc,
        }

        # 2. Relational sensors (DMGT U2)
        linked = self.relation_manager.get_linked_accounts(sender.account_id)

        # 3. Graph structural sensors (ADSA U2)
        has_cycle, cycle_path = self.cycle_detector.check_if_edge_creates_cycle(
            source=txn.sender_id,
            target=txn.receiver_id,
            max_depth=4,
        )

        fan_in_anom, _, _ = self.flow_analyzer.detect_fan_in_anomaly(
            node_id=txn.receiver_id,
            in_degree_threshold=2,
        )

        mule_anom, _, _ = self.flow_analyzer.detect_mule_pass_through(
            node_id=txn.sender_id,
        )

        hops_to_bl, _ = self.flow_analyzer.shortest_path_to_blacklisted(
            start_node=txn.sender_id,
            blacklisted_nodes=self.blacklisted_accounts,
            max_hops=3,
        )

        return Percept(
            transaction=txn,
            sender_account=sender,
            receiver_account=receiver,
            timestamp=txn.timestamp,
            proposition_truth_values=assignment,
            linked_accounts=linked,
            involves_cycle=has_cycle,
            cycle_nodes=cycle_path,
            fan_in_anomaly=fan_in_anom,
            mule_pass_through=mule_anom,
            hops_to_blacklist=hops_to_bl,
        )

    def calculate_posterior_fraud_probability(self, percept: Percept) -> Tuple[float, List[str], List[str]]:
        """Combines multiple independent signals into posterior fraud probability P(Fraud | Percept)."""
        audit_trail: List[str] = []

        # 1. DMGT U1: Propositional Logic Engine
        fired_flags, logic_risk, logic_traces = self.logic_engine.evaluate_all(percept.proposition_truth_values)
        for trace in logic_traces:
            audit_trail.append(f"[DMGT-U1 Logic] {trace}")

        # 2. ADSA U2: Graph Network Structural Risk
        graph_risk = 0.0
        if percept.involves_cycle:
            graph_risk += 0.50
            cycle_str = " -> ".join(percept.cycle_nodes)
            audit_trail.append(f"[ADSA-U2 Graph] Circular layering detected! Path: {cycle_str}")
            fired_flags.append("GRAPH_CIRCULAR_CYCLE_DETECTED")

        if percept.fan_in_anomaly:
            graph_risk += 0.35
            audit_trail.append(f"[ADSA-U2 Graph] Smurfing/Fan-In velocity anomaly at receiver: {percept.transaction.receiver_id}")
            fired_flags.append("GRAPH_SMURFING_FAN_IN_DETECTED")

        if percept.mule_pass_through:
            graph_risk += 0.30
            audit_trail.append(f"[ADSA-U2 Graph] Mule pass-through turnover detected at sender: {percept.transaction.sender_id}")
            fired_flags.append("GRAPH_MULE_TURNOVER_DETECTED")

        if percept.hops_to_blacklist is not None:
            if percept.hops_to_blacklist == 0:
                graph_risk += 0.95
                audit_trail.append("[ADSA-U2 Graph] SENDER IS ON FRAUD BLACKLIST!")
                fired_flags.append("SENDER_IN_FRAUD_BLACKLIST")
            elif percept.hops_to_blacklist == 1:
                graph_risk += 0.45
                audit_trail.append("[ADSA-U2 Graph] Direct 1-hop link to a blacklisted fraudulent account.")
                fired_flags.append("PROXIMITY_TO_BLACKLISTED_1HOP")
            elif percept.hops_to_blacklist == 2:
                graph_risk += 0.20
                audit_trail.append("[ADSA-U2 Graph] 2-hop proximity to blacklisted node.")
                fired_flags.append("PROXIMITY_TO_BLACKLISTED_2HOP")

        # 3. DMGT U2: Relational Equivalence Classes
        relation_risk = 0.0
        compromised_relatives = percept.linked_accounts.intersection(self.blacklisted_accounts)
        if compromised_relatives:
            relation_risk += 0.70
            audit_trail.append(
                f"[DMGT-U2 Relations] Equivalence Class [x] includes compromised accounts: {compromised_relatives}"
            )
            fired_flags.append("RELATION_EQUIVALENCE_COMPROMISED_LINK")
        elif len(percept.linked_accounts) >= 2:
            relation_risk += 0.35
            audit_trail.append(
                f"[DMGT-U2 Relations] Account shares device/IP/identity with {len(percept.linked_accounts)} accounts ({percept.linked_accounts})."
            )
            fired_flags.append("RELATION_SYNTHETIC_RING_SUSPECT")

        # Prior probability baseline P(Fraud) = 0.02
        p_base = 0.02
        # Weighted ensemble combining logic, graph, and relations
        posterior = p_base + 0.35 * logic_risk + 0.45 * min(1.0, graph_risk) + 0.25 * min(1.0, relation_risk)

        # If sender is directly blacklisted, posterior risk is near certainty (>= 0.95)
        if percept.hops_to_blacklist == 0 or percept.sender_account.is_blacklisted:
            posterior = max(posterior, 0.95)

        posterior = max(0.001, min(0.999, posterior))

        audit_trail.append(
            f"[Ensemble Synthesis] LogicRisk={logic_risk:.2f}, GraphRisk={graph_risk:.2f}, "
            f"RelationRisk={relation_risk:.2f} => P(Fraud)={posterior:.3f}"
        )
        return posterior, fired_flags, audit_trail

    def evaluate_expected_utility(self, p_fraud: float, amount: float) -> Dict[ActionType, float]:
        """Calculates Expected Utility EU(a) for each available action (AI U1 Rationality).

        Utility Matrix:
        State: FRAUD (probability p) vs LEGITIMATE (probability 1 - p)

        Action APPROVE:
          - If Fraud: Bank loses transaction amount (-amount)
          - If Legit: Bank earns transaction fee / goodwill (+0.01 * amount)

        Action FLAG_MANUAL_REVIEW:
          - If Fraud: Saves amount minus manual review labor cost (-review_cost)
          - If Legit: Customer experiences mild delay (-0.02 * amount - review_cost)

        Action FREEZE_ACCOUNT:
          - If Fraud: Saves full amount (+amount)
          - If Legit: Severe false-positive customer dissatisfaction penalty (-0.25 * amount - 100)
        """
        p_legit = 1.0 - p_fraud

        # EU(APPROVE) = p * (-amount) + (1-p) * (0.01 * amount)
        eu_approve = p_fraud * (-amount) + p_legit * (0.01 * amount)

        # EU(FLAG_MANUAL_REVIEW) = p * (amount * 0.90 - review_cost) + (1-p) * (-review_cost - 0.02 * amount)
        eu_review = p_fraud * (amount * 0.90 - self.review_cost) + p_legit * (
            -self.review_cost - 0.02 * amount
        )

        # EU(FREEZE_ACCOUNT) = p * (amount) + (1-p) * (-0.25 * amount - 100.0)
        eu_freeze = p_fraud * (amount) + p_legit * (-0.25 * amount - 100.0)

        return {
            ActionType.APPROVE: round(eu_approve, 2),
            ActionType.FLAG_MANUAL_REVIEW: round(eu_review, 2),
            ActionType.FREEZE_ACCOUNT: round(eu_freeze, 2),
        }

    def decide(self, txn: Transaction, sender: Account, receiver: Optional[Account]) -> DecisionOutcome:
        """Rational Agent Decision Function: f: P* -> A.

        Selects optimal action: a* = argmax_{a in Actions} EU(a).
        """
        percept = self.perceive(txn, sender, receiver)
        p_fraud, fired_rules, audit_trail = self.calculate_posterior_fraud_probability(percept)
        utilities = self.evaluate_expected_utility(p_fraud, txn.amount)

        # Rational choice: argmax EU(a)
        best_action = max(utilities.keys(), key=lambda a: utilities[a])

        # Assign risk tier
        if p_fraud < 0.15:
            tier = RiskTier.LOW
        elif p_fraud < 0.45:
            tier = RiskTier.MEDIUM
        elif p_fraud < 0.80:
            tier = RiskTier.HIGH
        else:
            tier = RiskTier.CRITICAL

        # Update transaction object
        txn.risk_score = p_fraud
        for r in fired_rules:
            txn.add_flag(r)

        if best_action == ActionType.APPROVE:
            txn.mark_approved()
        elif best_action == ActionType.FLAG_MANUAL_REVIEW:
            txn.mark_flagged()
        else:
            txn.mark_blocked()

        # Update graph state upon decision
        self.graph.add_transaction_edge(
            edge_id=txn.txn_id,
            source=txn.sender_id,
            target=txn.receiver_id,
            amount=txn.amount,
            timestamp=txn.timestamp,
        )

        audit_trail.append(
            f"[AI Rational Decision] Optimal Action={best_action.value} with Max Expected Utility="
            f"${utilities[best_action]:.2f}. (Utilities: {utilities})"
        )

        return DecisionOutcome(
            action=best_action,
            risk_tier=tier,
            posterior_fraud_probability=p_fraud,
            expected_utilities=utilities,
            fired_rules=fired_rules,
            audit_trail=audit_trail,
        )
