-- ============================================================================
-- 01_SNOWFLAKE_DDL.SQL
-- Snowflake Cloud Data Warehouse / Lakehouse Dimensional Architecture
-- ============================================================================

CREATE DATABASE IF NOT EXISTS BANK_FRAUD_DW;
CREATE SCHEMA IF NOT EXISTS BANK_FRAUD_DW.ANALYTICS;
USE SCHEMA BANK_FRAUD_DW.ANALYTICS;

-- 1. Dimension Table: Accounts & KYC Profiling
CREATE OR REPLACE TABLE DIM_ACCOUNTS (
    ACCOUNT_KEY         INT AUTOINCREMENT PRIMARY KEY,
    ACCOUNT_ID          VARCHAR(64) UNIQUE NOT NULL,
    HOLDER_NAME         VARCHAR(128) NOT NULL,
    INITIAL_BALANCE     DECIMAL(18, 2) DEFAULT 0.00,
    CURRENT_BALANCE     DECIMAL(18, 2) DEFAULT 0.00,
    KYC_TIER            VARCHAR(32) DEFAULT 'TIER_1_UNVERIFIED',
    DEVICE_FINGERPRINT  VARCHAR(128),
    IP_ADDRESS          VARCHAR(64),
    NATIONAL_ID_ENCRYPTED VARCHAR(256),
    IS_BLACKLISTED      BOOLEAN DEFAULT FALSE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Fact Table: Screened Financial Transactions
CREATE OR REPLACE TABLE FACT_TRANSACTIONS (
    TXN_KEY             INT AUTOINCREMENT PRIMARY KEY,
    SNOWFLAKE_TXN_ID    VARCHAR(64) UNIQUE NOT NULL,
    SENDER_ACCOUNT_ID   VARCHAR(64) REFERENCES DIM_ACCOUNTS(ACCOUNT_ID),
    RECEIVER_ACCOUNT_ID VARCHAR(64) REFERENCES DIM_ACCOUNTS(ACCOUNT_ID),
    TRANSACTION_AMOUNT  DECIMAL(18, 2) NOT NULL,
    TRANSACTION_TIME    TIMESTAMP_NTZ NOT NULL,
    CHANNEL             VARCHAR(32),
    LOCATION_COUNTRY    VARCHAR(64),
    DEVICE_ID           VARCHAR(128),
    IP_ADDRESS          VARCHAR(64),
    P_FRAUD_PROBABILITY FLOAT,
    RISK_TIER           VARCHAR(16),
    RATIONAL_ACTION     VARCHAR(32),
    SETTLEMENT_STATUS   VARCHAR(32),
    FIRED_RULES_JSON    VARIANT,
    HMAC_SIGNATURE      VARCHAR(128),
    INGESTED_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Cluster key for high-performance temporal range queries
ALTER TABLE FACT_TRANSACTIONS CLUSTER BY (TRANSACTION_TIME, RISK_TIER);

-- 3. Dimension Table: Anomaly Audit Telemetry & Logic Rules
CREATE OR REPLACE TABLE DIM_ANOMALY_AUDIT (
    AUDIT_ID            INT AUTOINCREMENT PRIMARY KEY,
    SNOWFLAKE_TXN_ID    VARCHAR(64) REFERENCES FACT_TRANSACTIONS(SNOWFLAKE_TXN_ID),
    SUBSYSTEM           VARCHAR(32), -- 'DMGT_LOGIC', 'ADSA_GRAPH', 'AI_RATIONAL'
    TRACE_DETAIL        VARCHAR(4096),
    BLOCK_HASH          VARCHAR(64),
    PREV_HASH           VARCHAR(64),
    LOGGED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Staging Table: Real-Time Streaming Ingestion
CREATE OR REPLACE TABLE STAGING_TRANSACTIONS (
    INGESTION_ID        INT AUTOINCREMENT PRIMARY KEY,
    RAW_PAYLOAD         VARIANT,
    INGESTED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. Snowflake CDC Stream & Continuous Task
CREATE OR REPLACE STREAM STREAM_SUSPICIOUS_TXNS ON TABLE FACT_TRANSACTIONS;

CREATE OR REPLACE TASK TASK_AUTO_FLAG_SUSPICIOUS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('STREAM_SUSPICIOUS_TXNS')
AS
    INSERT INTO DIM_ANOMALY_AUDIT (SNOWFLAKE_TXN_ID, SUBSYSTEM, TRACE_DETAIL)
    SELECT SNOWFLAKE_TXN_ID, 'SNOWFLAKE_STREAM_ALERT', 'Automated Stream Task detected high-risk transaction'
    FROM STREAM_SUSPICIOUS_TXNS
    WHERE RISK_TIER IN ('HIGH', 'CRITICAL');
