!======================================================================
! MODULE: RISK_MONTE_CARLO
! PURPOSE: HIGH-PRECISION NUMERICAL VALUE-AT-RISK (VaR) & EXPECTED
!          SHORTFALL (CVaR) COMPUTATION FOR BANK TRANSACTION ANOMALIES
! STANDARD: FORTRAN 90/2003 NUMERICAL SPECIFICATION
!======================================================================
MODULE RISK_MONTE_CARLO
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: COMPUTE_VAR_CVAR, SIMULATE_PORTFOLIO_RISK

  INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(15, 307)

CONTAINS

  SUBROUTINE COMPUTE_VAR_CVAR(N_SIMS, LOSS_ARRAY, CONFIDENCE_LEVEL, VAR_OUT, CVAR_OUT)
    INTEGER, INTENT(IN) :: N_SIMS
    REAL(DP), DIMENSION(N_SIMS), INTENT(INOUT) :: LOSS_ARRAY
    REAL(DP), INTENT(IN) :: CONFIDENCE_LEVEL
    REAL(DP), INTENT(OUT) :: VAR_OUT, CVAR_OUT

    INTEGER :: CUTOFF_INDEX, I
    REAL(DP) :: TAIL_SUM

    ! Sort loss distribution in ascending order
    CALL QUICKSORT_REAL(LOSS_ARRAY, 1, N_SIMS)

    ! Percentile index for Value-at-Risk (e.g. 99% quantile)
    CUTOFF_INDEX = INT(REAL(N_SIMS, DP) * CONFIDENCE_LEVEL)
    IF (CUTOFF_INDEX < 1) CUTOFF_INDEX = 1
    IF (CUTOFF_INDEX > N_SIMS) CUTOFF_INDEX = N_SIMS

    VAR_OUT = LOSS_ARRAY(CUTOFF_INDEX)

    ! Expected Shortfall (CVaR) = Mean of losses exceeding VaR threshold
    TAIL_SUM = 0.0_DP
    DO I = CUTOFF_INDEX, N_SIMS
      TAIL_SUM = TAIL_SUM + LOSS_ARRAY(I)
    END DO

    CVAR_OUT = TAIL_SUM / REAL(N_SIMS - CUTOFF_INDEX + 1, DP)
  END SUBROUTINE COMPUTE_VAR_CVAR

  SUBROUTINE SIMULATE_PORTFOLIO_RISK(BASE_AMOUNT, RISK_PROBABILITY, N_SIMS, VAR_99, CVAR_99)
    REAL(DP), INTENT(IN) :: BASE_AMOUNT, RISK_PROBABILITY
    INTEGER, INTENT(IN) :: N_SIMS
    REAL(DP), INTENT(OUT) :: VAR_99, CVAR_99

    REAL(DP), ALLOCATABLE :: LOSSES(:)
    INTEGER :: I
    REAL(DP) :: U, SIMULATED_LOSS

    ALLOCATE(LOSSES(N_SIMS))

    ! Monte Carlo Simulation of Stochastic Fraud Losses
    DO I = 1, N_SIMS
      CALL RANDOM_NUMBER(U)
      IF (U < RISK_PROBABILITY) THEN
        ! Heavy-tailed Pareto / Log-normal loss multiplier under fraud event
        SIMULATED_LOSS = BASE_AMOUNT * (1.0_DP + U * 2.5_DP)
      ELSE
        SIMULATED_LOSS = 0.0_DP
      END IF
      LOSSES(I) = SIMULATED_LOSS
    END DO

    CALL COMPUTE_VAR_CVAR(N_SIMS, LOSSES, 0.99_DP, VAR_99, CVAR_99)
    DEALLOCATE(LOSSES)
  END SUBROUTINE SIMULATE_PORTFOLIO_RISK

  RECURSIVE SUBROUTINE QUICKSORT_REAL(A, FIRST, LAST)
    REAL(DP), DIMENSION(:), INTENT(INOUT) :: A
    INTEGER, INTENT(IN) :: FIRST, LAST
    REAL(DP) :: X, T
    INTEGER :: I, J

    IF (FIRST < LAST) THEN
      X = A((FIRST + LAST) / 2)
      I = FIRST
      J = LAST
      DO
        DO WHILE (A(I) < X)
          I = I + 1
        END DO
        DO WHILE (X < A(J))
          J = J - 1
        END DO
        IF (I >= J) EXIT
        T = A(I); A(I) = A(J); A(J) = T
        I = I + 1
        J = J - 1
      END DO
      IF (FIRST < I - 1) CALL QUICKSORT_REAL(A, FIRST, I - 1)
      IF (J + 1 < LAST)  CALL QUICKSORT_REAL(A, J + 1, LAST)
    END IF
  END SUBROUTINE QUICKSORT_REAL

END MODULE RISK_MONTE_CARLO
